import G6 from "@antv/g6"
const toolList = [
  // {
  //     name: 'logo',
  //     label: '',
  //     type: 'text',
  //     icon: '',
  //     enable: true,
  //     disabled: false,
  //     mode: ['edit', 'preview'],
  //     divider: false,
  //     shortcuts: '',
  //     toolbar: {
  //         enable: true,
  //         position: 'left'
  //     },
  //     contextmenu: {
  //         enable: false,
  //         target: []
  //     }
  // },
  {
    name: "groupline",
    label: "框选",
    type: "crop",
    icon: " el-icon-crop",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: false,
      target: [],
    },
  },
  {
    name: "undo",
    label: "撤销",
    type: "normal",
    icon: "iconfont-flow icon-undo",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: [],
    },
  },
  {
    name: "redo",
    label: "重做",
    type: "normal",
    icon: "iconfont-flow icon-redo",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: true,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: [],
    },
  },
  {
    name: "copy",
    label: "复制",
    type: "normal",
    icon: "iconfont-flow icon-copy",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    // FIXME 通用mod助手用于设置跨平台快捷方式，用于将command+c在Windows和Linux上映射到ctrl+c
    shortcuts: "mod+c",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
  },
  {
    name: "paste",
    label: "粘贴",
    type: "normal",
    icon: "iconfont-flow icon-paste",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "mod+v",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas", "node", "edge"],
    },
  },
  {
    name: "delete",
    label: "删除",
    type: "normal",
    icon: "iconfont-flow icon-delete",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: true,
    shortcuts: "del",
    toolbar: {
      enable: false,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
  },
  {
    name: "clear",
    label: "清空",
    type: "normal",
    icon: "iconfont-flow icon-clear",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: true,
    shortcuts: "ctrl+shift+c",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas"],
    },
  },
  {
    name: "zoom",
    label: "缩放",
    type: "dropdown-list",
    icon: "iconfont-flow icon-zoom",
    enable: true,
    disabled: false,
    mode: ["edit", "preview"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: false,
      target: [],
    },
    // 默认选中项index
    selected: 0,
    // 锁定下拉菜单label
    lockLabel: true,
    // 子节点
    children: [
      {
        name: "25%",
        label: "25%",
        lang: "",
        type: "normal",
        icon: "",
        data: 0.25,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "50%",
        label: "50%",
        lang: "",
        type: "normal",
        icon: "",
        data: 0.5,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "75%",
        label: "75%",
        lang: "",
        type: "normal",
        icon: "",
        data: 0.75,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "100%",
        label: "100%",
        lang: "",
        type: "normal",
        icon: "",
        data: 1,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "125%",
        label: "125%",
        lang: "",
        type: "normal",
        icon: "",
        data: 1.25,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "150%",
        label: "150%",
        lang: "",
        type: "normal",
        icon: "",
        data: 1.5,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "200%",
        label: "200%",
        lang: "",
        type: "normal",
        icon: "",
        data: 2,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "300%",
        label: "300%",
        lang: "",
        type: "normal",
        icon: "",
        data: 3,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "400%",
        label: "400%",
        lang: "",
        type: "normal",
        icon: "",
        data: 4,
        enable: true,
        disabled: false,
        divider: false,
      },
    ],
  },
  {
    name: "zoomIn",
    label: "放大",
    type: "normal",
    icon: "iconfont-flow icon-zoom-in",
    enable: true,
    disabled: false,
    mode: ["edit", "preview"],
    divider: false,
    // FIXME mod+= 用于支持主键盘区的+，mod+plus用于支持数字键盘区的+
    shortcuts: ["mod+=", "mod+plus"],
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas", "node", "edge"],
    },
  },
  {
    name: "zoomOut",
    label: "缩小",
    type: "normal",
    icon: "iconfont-flow icon-zoom-out",
    enable: true,
    disabled: false,
    mode: ["edit", "preview"],
    divider: false,
    shortcuts: "mod+-",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas", "node", "edge"],
    },
  },
  {
    name: "fit",
    label: "适应屏幕",
    type: "normal",
    icon: "iconfont-flow icon-fit",
    enable: true,
    disabled: false,
    mode: ["edit", "preview"],
    divider: false,
    shortcuts: "mod+0",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas", "node", "edge"],
    },
  },
  {
    name: "actualSize",
    label: "实际大小",
    type: "normal",
    icon: "iconfont-flow icon-actual-size",
    enable: true,
    disabled: false,
    mode: ["edit", "preview"],
    divider: true,
    shortcuts: "mod+1",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas", "node", "edge"],
    },
  },
  {
    name: "fill",
    label: "填充颜色",
    type: "dropdown-color-picker",
    icon: "iconfont-flow icon-fill",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
  },
  {
    name: "lineColor",
    label: "线条颜色",
    type: "dropdown-color-picker",
    icon: "iconfont-flow icon-line-color",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
  },
  {
    name: "lineWidth",
    label: "线条宽度",
    type: "dropdown-list",
    icon: "iconfont-flow icon-line-width",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
    // 默认选中项index
    selected: 0,
    lockLabel: true,
    // 子节点
    children: [
      {
        name: 1,
        label: "1px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 2,
        label: "2px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 3,
        label: "3px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 4,
        label: "4px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 5,
        label: "5px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 6,
        label: "6px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 7,
        label: "7px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 8,
        label: "8px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 9,
        label: "9px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: 10,
        label: "10px",
        lang: "",
        type: "normal",
        icon: "",
        enable: true,
        disabled: false,
        divider: false,
      },
    ],
  },
  {
    name: "lineStyle",
    label: "线条样式",
    type: "dropdown-list",
    icon: "iconfont-flow icon-line-style",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: true,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
    // 默认选中项index
    selected: 0,
    lockLabel: false,
    // 子节点
    children: [
      {
        name: "solid",
        label: "solid",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-solid",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "dashed",
        label: "dashed",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-dashed",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "dot",
        label: "dot",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-dot",
        enable: true,
        disabled: false,
        divider: false,
      },
    ],
  },
  {
    name: "lineType",
    label: "线条类型",
    type: "dropdown-list",
    icon: "",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["edge"],
    },
    // 默认选中项index
    selected: 0,
    lockLabel: false,
    // 子节点
    children: [
      {
        name: "a-line",
        label: "line",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-flow-line",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "a-broken",
        label: "broken",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-flow-broken",
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "x-cubic",
        label: "cubic",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-flow-curve",
        enable: true,
        disabled: false,
        divider: false,
      },
    ],
  },
  {
    name: "startArrow",
    label: "起点",
    type: "dropdown-list",
    icon: "",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["edge"],
    },
    // 默认选中项index
    selected: 0,
    lockLabel: false,
    // 子节点
    children: [
      {
        name: "none",
        label: "none",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-solid",
        style: {},
        data: false,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "normalArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-normal",
        style: {},
        data: true,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "triangleArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-triangle",
        style: {},
        data: {
          path: G6.Arrow.triangle(10, 20, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "veeArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-vee",
        style: {},
        data: {
          path: G6.Arrow.vee(10, 20, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "circleArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-circle",
        style: {},
        data: {
          path: G6.Arrow.circle(10, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "rectArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-rect",
        style: {},
        data: {
          path: G6.Arrow.rect(10, 20, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "triangleRectArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-triangle-rect",
        style: {},
        data: {
          path: G6.Arrow.triangleRect(15, 15, 15, 3, 5, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
    ],
  },
  {
    name: "endArrow",
    label: "终点",
    type: "dropdown-list",
    icon: "",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: true,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["edge"],
    },
    // 默认选中项index
    selected: 0,
    lockLabel: false,
    // 子节点
    children: [
      {
        name: "none",
        label: "none",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-solid",
        style: {},
        data: false,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "normalArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-normal",
        style: {},
        data: true,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "triangleArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-triangle",
        style: {},
        data: {
          path: G6.Arrow.triangle(10, 20, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "veeArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-vee",
        style: {},
        data: {
          path: G6.Arrow.vee(10, 20, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "circleArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-circle",
        style: {},
        data: {
          path: G6.Arrow.circle(10, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "rectArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-rect",
        style: {},
        data: {
          path: G6.Arrow.rect(10, 20, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "triangleRectArrow",
        label: "",
        lang: "",
        type: "normal",
        icon: " edge-arrow edge-arrow-triangle-rect",
        style: {},
        data: {
          path: G6.Arrow.triangleRect(15, 15, 15, 3, 5, 0),
          d: 0,
        },
        enable: true,
        disabled: false,
        divider: false,
      },
    ],
  },
  {
    name: "toFront",
    label: "置于顶层",
    type: "normal",
    icon: "iconfont-flow icon-to-front",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
  },
  {
    name: "toBack",
    label: "置于底层",
    type: "normal",
    icon: "iconfont-flow icon-to-back",
    enable: true,
    disabled: false,
    mode: ["edit"],
    divider: true,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["node", "edge"],
    },
  },
  {
    name: "fullscreen",
    label: "全屏",
    type: "normal",
    icon: "iconfont-flow icon-full-screen",
    enable: true,
    disabled: false,
    mode: ["edit", "preview"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas", "node", "edge"],
    },
  },
  {
    name: "download",
    label: "下载",
    type: "dropdown-list",
    icon: "iconfont-flow icon-download",
    enable: true,
    disabled: false,
    mode: ["edit", "preview"],
    divider: false,
    shortcuts: "",
    toolbar: {
      enable: true,
      position: "center",
    },
    contextmenu: {
      enable: true,
      target: ["canvas", "node", "edge"],
    },
    // 默认选中项index
    selected: 0,
    lockLabel: true,
    // 子节点
    children: [
      {
        name: "image",
        label: "Image",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-image",
        style: {},
        data: false,
        enable: true,
        disabled: false,
        divider: false,
      },
      {
        name: "json",
        label: "Json",
        lang: "",
        type: "normal",
        icon: "iconfont-flow icon-json",
        style: {},
        data: false,
        enable: true,
        disabled: false,
        divider: false,
      },
    ],
  },
  // {
  //     name: 'save',
  //     label: '保存',
  //     lang: 'common.submit',
  //     type: 'button',
  //     icon: '',
  //     enable: true,
  //     disabled: false,
  //     mode: ['edit'],
  //     divider: false,
  //     shortcuts: '',
  //     toolbar: {
  //         enable: true,
  //         position: 'right'
  //     },
  //     contextmenu: {
  //         enable: true,
  //         target: ['canvas', 'node', 'edge']
  //     }
  // },
  // {
  //   name: 'language',
  //   label: 'language',
  //   lang: 'flowchart.L10026',
  //   type: 'dropdown-list',
  //   icon: 'language',
  //   enable: true,
  //   disabled: false,
  //   mode: ['edit', 'preview'],
  //   divider: false,
  //   shortcuts: '',
  //   toolbar: {
  //     enable: true,
  //     position: 'center'
  //   },
  //   contextmenu: {
  //     enable: true,
  //     target: ['canvas', 'node', 'edge']
  //   },
  //   // 默认选中项index
  //   selected: 0,
  //   lockLabel: true,
  //   // 子节点
  //   children: [
  //     {
  //       name: 'zh-CN',
  //       label: '简体中文',
  //       lang: '',
  //       type: 'normal',
  //       icon: '',
  //       style: {},
  //       data: false,
  //       enable: true,
  //       disabled: false,
  //       divider: false
  //     },
  //     {
  //       name: 'en-US',
  //       label: 'English',
  //       lang: '',
  //       type: 'normal',
  //       icon: '',
  //       style: {},
  //       data: false,
  //       enable: true,
  //       disabled: false,
  //       divider: false
  //     }
  //   ]
  // },
  // {
  //   name: 'github',
  //   label: 'github',
  //   lang: 'flowchart.L10027',
  //   type: 'link',
  //   icon: 'github',
  //   link: 'github',
  //   enable: true,
  //   disabled: false,
  //   mode: ['edit', 'preview'],
  //   divider: false,
  //   shortcuts: '',
  //   toolbar: {
  //     enable: true,
  //     position: 'right'
  //   },
  //   contextmenu: {
  //     enable: true,
  //     target: ['canvas', 'node', 'edge']
  //   }
  // },
  // {
  //   name: 'feedback',
  //   label: 'feedback',
  //   lang: 'flowchart.L10028',
  //   type: 'link',
  //   icon: 'feedback',
  //   link: 'config.system.feedback',
  //   enable: true,
  //   disabled: false,
  //   mode: ['edit', 'preview'],
  //   divider: false,
  //   shortcuts: '',
  //   toolbar: {
  //     enable: true,
  //     position: 'right'
  //   },
  //   contextmenu: {
  //     enable: true,
  //     target: ['canvas', 'node', 'edge']
  //   }
  // }
]

export default toolList
